### ISSUE TITLE
Map Escape as CapsLock?

### ISSUE THREAD

**Issue by searene** [kshenoy/CapsUnlocked#1]
Can you also map Escape as CapsLock in the script? So I don't need to hold Shift all the time when I'm writing SQL(SQL statements are uppercase mostly).

Anyway, thanks for this amazing script, it makes my life a lot easier in Windows.

**Comment by kshenoy** [comment]
Thanks, I'm glad to know that you find it useful. I assume you made this same request on reddit as well. If not, this is an amazing coincidence. Copy-pasting my response from reddit for the sake of completeness.

You can use `LCtrl+CapsLock` to toggle CapsLock. Just make sure that you press LCtrl before pressing `CapsLock`. If this doesn't work please file a separate bug.

I'm reluctant to modify Escape because if I were to do so and we tap CapsLock, because of the original behavior, it will generate an Escape and I'll have to put in more code to ensure that it doesn't trigger our new `Escape ==> CapsLock` mapping. In short, it makes the script more intrusive without adding any new functionality.
